services:
  # auth-service:
  #   build:
  #     context: ./WaterReminder.Auth
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:80"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:80

  backend-service:
    build:
      context: ./WaterReminder.API
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
